### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by brayn003** [teknack/sixty-seconds#3]
![screenshot from 2016-01-01 22 04 52](https://cloud.githubusercontent.com/assets/8724051/12071453/d9d1b236-b0d3-11e5-8178-8b3042b9c1f6.png)
Missing file water.jpg
Missing file oxygen.jpg

**Comment by NiggaHas69** [comment]
I wish I knew how to upload a folder through the web interface.

**Comment by brayn003** [comment]
Did you see the videos?

**Comment by NiggaHas69** [comment]
I did that day. I might have to go re-watch.
